// Generates src/epistemic/logodds-table.ts: milli-log-odds for every integer percentage 1..99,
// mlo(p) = round(1000 * ln(p / (100 - p))). Committed output; rerun to verify: node scripts/gen-logodds.mjs --check
import fs from 'node:fs';

const values = [];
for (let p = 1; p <= 99; p++) values.push(Math.round(1000 * Math.log(p / (100 - p))));
const out = `// GENERATED by scripts/gen-logodds.mjs — do not edit by hand.
// MLO[p] = round(1000 * ln(p / (100 - p))) for p in 1..99; index 0 is unused.
export const MLO: readonly number[] = Object.freeze([0, ${values.join(', ')}]);
`;
const target = new URL('../src/epistemic/logodds-table.ts', import.meta.url);
if (process.argv.includes('--check')) {
  const cur = fs.readFileSync(target, 'utf8');
  if (cur !== out) { console.error('logodds-table.ts is stale: run node scripts/gen-logodds.mjs'); process.exit(1); }
  console.log('logodds-table.ts up to date');
} else {
  fs.writeFileSync(target, out);
  console.log(`wrote ${values.length} values; mlo(1)=${values[0]} mlo(50)=${values[49]} mlo(95)=${values[94]} mlo(99)=${values[98]}`);
}
